AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template to launch 10 VMs in the current region'
Parameters:
  KeyName:
    ConstraintDescription: must be the name of an existing EC2 Keypair in this region
    Description: Name of a KeyPair that already exists in this region
    Type: AWS::EC2::KeyPair::KeyName
  InstanceTypeWindows:
    AllowedValues:
      - t3.xlarge
    Default: t3.xlarge
    Description: Instance type for Windows instance types
    ConstraintDescription: Must be a valid EC2 instance type
    Type: String
  InstanceTypeLinux:
    AllowedValues:
      - t2.micro
    Default: t2.micro
    Description: Instance type for Linux instance types
    ConstraintDescription: Must be a valid EC2 instance type
    Type: String
  SSHLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IPv4 CIDR range of the form x.x.x.x/x
    Default: 0.0.0.0/0
    Description: IP range allowed to SSH to this EC2 instance
    Type: String
    MinLength: '9'
    MaxLength: '18'
  RDPLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid IPv4 CIDR range of the form x.x.x.x/x
    Default: 0.0.0.0/0
    Description: IP range allowed to RDP to this EC2 instance
    Type: String
    MinLength: '9'
    MaxLength: '18'
Mappings:
  AWSInstanceType2Arch:
    t2.micro:
      Arch: HVM64
    t3.xlarge:
      Arch: HVM64
  AWSRegionArch2AMI:
    ap-northeast-1:
      HVM64: ami-0af1df87db7b650f4
    ap-northeast-2:
      HVM64: ami-0a93a08544874b3b7
    ap-southeast-1:
      HVM64: ami-0f02b24005e4aec36
    ap-southeast-2:
      HVM64: ami-0fad060fc1dafbad1
    us-east-2:
      HVM64: ami-0e38b48473ea57778
    us-east-1:
      HVM64: ami-0a887e401f7654935
    us-west-1:
      HVM64: ami-042171985f9a813af
    us-west-2:
      HVM64: ami-0c24523f82c0eb7d2
    ap-south-1:
      HVM64: ami-0d9462a653c34dab7
    ca-central-1:
      HVM64: ami-014f55f965f51c865
    eu-central-1:
      HVM64: ami-0df0e7600ad0913a9
    eu-west-1:
      HVM64: ami-0d4d506696fe4baf8
    eu-west-2:
      HVM64: ami-0389b2a3c4948b1a0
    eu-west-3:
      HVM64: ami-0fd9bce3a3384b635
    eu-north-1:
      HVM64: ami-0fab3541efaecf61a
    sa-east-1:
      HVM64: ami-080a223be3de0c3b8
Resources:
  Instance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !FindInMap 
        - AWSRegionArch2AMI
        - !Ref 'AWS::Region'
        - !FindInMap
          - AWSInstanceType2Arch
          - !Ref InstanceTypeWindows
          - Arch
      InstanceType:
        Ref: InstanceTypeWindows
      KeyName:
        Ref: KeyName
      SecurityGroups:
        Ref: CommonSecurityGroup
      Monitoring: False
      IAMInstanceProfile:
        Ref: SSMProfile
      Tags:
        - Key: swoMonitor
          Value: '1'
        - Key: Name
          Value: Instance1
      UserData:
        Fn::Base64:
          #!/bin/bash -xe
          yum update -y
          sudo yum install -y https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
          yum install mariadb mariadb-server -y
          nsystemctl start mariadb
          systemctl enable mariadb
  CommonSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Allow SSH and RDP access to the VM"
      SecurityGroupIngress:
        - CidrIp: !Ref SSHLocation
          FromPort: '22'
          ToPort: '22'
          IpProtocol: tcp
        - CidrIp: !Ref RDPLocation
          FromPort: '3389'
          ToPort: '3389'
          IpProtocol: tcp
  SSMProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName: ssmprofile
      Path: "/"
      Roles:
        -
          Ref: "SSMRole"
  SSMRole:
    Type: AWS::IAM::Role
    Properties:
      Description: Role for EC2 instance profile
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforSSM
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statememnt:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
              Action:
                - 'sts:AssumeRole'
      MaxSessionDuration: 3600
      RoleName: ssmrole